//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienMueble
    {
        public BienMueble()
        {
            this.AsignacionBienMueble = new HashSet<AsignacionBienMueble>();
        }
    
        public int IdBienMueble { get; set; }
        public int IdEstado { get; set; }
        public string Nombre { get; set; }
        public string UsuRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string UsuModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual ICollection<AsignacionBienMueble> AsignacionBienMueble { get; set; }
        public virtual Estado Estado { get; set; }
    }
}
