//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConceptoPago
    {
        public ConceptoPago()
        {
            this.SolicitudPagoServicio = new HashSet<SolicitudPagoServicio>();
        }
    
        public long Codigo { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<SolicitudPagoServicio> SolicitudPagoServicio { get; set; }
    }
}
