//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contribuyente
    {
        public Contribuyente()
        {
            this.SolicitudPagoServicio = new HashSet<SolicitudPagoServicio>();
        }
    
        public long CodContribuyente { get; set; }
        public string Nombre { get; set; }
        public string CodTipoDocumento { get; set; }
        public string NumDocumento { get; set; }
        public string Direccion { get; set; }
        public string TelefonoFijo { get; set; }
        public string TelefonoMovil { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual Multitabla Multitabla { get; set; }
        public virtual ICollection<SolicitudPagoServicio> SolicitudPagoServicio { get; set; }
    }
}
