//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expediente
    {
        public long NumeroExpediente { get; set; }
        public Nullable<System.DateTime> FechaExpediente { get; set; }
        public Nullable<long> NumeroSolicitud { get; set; }
        public string Tipo_Expediente { get; set; }
        public string Asunto { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual Multitabla Multitabla { get; set; }
        public virtual SolicitudInformacionMunicipal SolicitudInformacionMunicipal { get; set; }
    }
}
