//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UPC_MUNIEntities : DbContext
    {
        public UPC_MUNIEntities()
            : base("name=UPC_MUNIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AsignacionBienMueble> AsignacionBienMueble { get; set; }
        public DbSet<BienMueble> BienMueble { get; set; }
        public DbSet<Estado> Estado { get; set; }
        public DbSet<SolicitudAsignacionBienMueble> SolicitudAsignacionBienMueble { get; set; }
        public DbSet<UsuarioTrabajador> UsuarioTrabajador { get; set; }
        public DbSet<Area> Area { get; set; }
        public DbSet<Cargo> Cargo { get; set; }
        public DbSet<GrupoTabla> GrupoTabla { get; set; }
        public DbSet<Multitabla> Multitabla { get; set; }
        public DbSet<ConceptoPago> ConceptoPago { get; set; }
        public DbSet<ConceptoRecibo> ConceptoRecibo { get; set; }
        public DbSet<Contribuyente> Contribuyente { get; set; }
        public DbSet<FormaPago> FormaPago { get; set; }
        public DbSet<MovimientoCajaChica> MovimientoCajaChica { get; set; }
        public DbSet<PagoServicio> PagoServicio { get; set; }
        public DbSet<ReciboProvisional> ReciboProvisional { get; set; }
        public DbSet<SolicitudPagoServicio> SolicitudPagoServicio { get; set; }
        public DbSet<TipoCambio> TipoCambio { get; set; }
        public DbSet<Expediente> Expediente { get; set; }
        public DbSet<SolicitudInformacionMunicipal> SolicitudInformacionMunicipal { get; set; }
    }
}
