//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Multitabla
    {
        public Multitabla()
        {
            this.Contribuyente = new HashSet<Contribuyente>();
            this.Expediente = new HashSet<Expediente>();
            this.MovimientoCajaChica = new HashSet<MovimientoCajaChica>();
            this.MovimientoCajaChica1 = new HashSet<MovimientoCajaChica>();
            this.PagoServicio = new HashSet<PagoServicio>();
            this.PagoServicio1 = new HashSet<PagoServicio>();
            this.ReciboProvisional = new HashSet<ReciboProvisional>();
            this.SolicitudPagoServicio = new HashSet<SolicitudPagoServicio>();
            this.SolicitudInformacionMunicipal = new HashSet<SolicitudInformacionMunicipal>();
            this.SolicitudInformacionMunicipal1 = new HashSet<SolicitudInformacionMunicipal>();
            this.TipoCambio = new HashSet<TipoCambio>();
        }
    
        public string IdMultitabla { get; set; }
        public string IdGrupo { get; set; }
        public string NombreValor { get; set; }
        public string DescripcionLarga { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual GrupoTabla GrupoTabla { get; set; }
        public virtual ICollection<Contribuyente> Contribuyente { get; set; }
        public virtual ICollection<Expediente> Expediente { get; set; }
        public virtual ICollection<MovimientoCajaChica> MovimientoCajaChica { get; set; }
        public virtual ICollection<MovimientoCajaChica> MovimientoCajaChica1 { get; set; }
        public virtual ICollection<PagoServicio> PagoServicio { get; set; }
        public virtual ICollection<PagoServicio> PagoServicio1 { get; set; }
        public virtual ICollection<ReciboProvisional> ReciboProvisional { get; set; }
        public virtual ICollection<SolicitudPagoServicio> SolicitudPagoServicio { get; set; }
        public virtual ICollection<SolicitudInformacionMunicipal> SolicitudInformacionMunicipal { get; set; }
        public virtual ICollection<SolicitudInformacionMunicipal> SolicitudInformacionMunicipal1 { get; set; }
        public virtual ICollection<TipoCambio> TipoCambio { get; set; }
    }
}
