//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoServicio
    {
        public long NumeroPago { get; set; }
        public Nullable<long> NumSolicitudPago { get; set; }
        public Nullable<long> CodFormaPago { get; set; }
        public Nullable<long> CodTipoCambio { get; set; }
        public string CodMonedaPago { get; set; }
        public Nullable<decimal> MontoPago { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public string CodEstadoPago { get; set; }
    
        public virtual Multitabla Multitabla { get; set; }
        public virtual Multitabla Multitabla1 { get; set; }
        public virtual FormaPago FormaPago { get; set; }
        public virtual TipoCambio TipoCambio { get; set; }
        public virtual SolicitudPagoServicio SolicitudPagoServicio { get; set; }
    }
}
