//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReciboProvisional
    {
        public long NumeroRecibo { get; set; }
        public Nullable<long> CodConceptoRecibo { get; set; }
        public string Motivo { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public string CodEstado { get; set; }
        public Nullable<int> CodTrabajador { get; set; }
        public string MotivoRechazo { get; set; }
    
        public virtual UsuarioTrabajador UsuarioTrabajador { get; set; }
        public virtual Multitabla Multitabla { get; set; }
        public virtual ConceptoRecibo ConceptoRecibo { get; set; }
    }
}
