//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudPagoServicio
    {
        public SolicitudPagoServicio()
        {
            this.PagoServicio = new HashSet<PagoServicio>();
        }
    
        public long NumSolicitudPago { get; set; }
        public Nullable<long> CodContribuyente { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public Nullable<long> CodConceptoPago { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Motivo { get; set; }
        public string CodEstadoSolicitud { get; set; }
    
        public virtual Multitabla Multitabla { get; set; }
        public virtual ConceptoPago ConceptoPago { get; set; }
        public virtual Contribuyente Contribuyente { get; set; }
        public virtual ICollection<PagoServicio> PagoServicio { get; set; }
    }
}
