//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioTrabajador
    {
        public UsuarioTrabajador()
        {
            this.AsignacionBienMueble = new HashSet<AsignacionBienMueble>();
            this.ReciboProvisional = new HashSet<ReciboProvisional>();
            this.SolicitudInformacionMunicipal = new HashSet<SolicitudInformacionMunicipal>();
        }
    
        public int IdUsuarioTrabajador { get; set; }
        public int IdArea { get; set; }
        public int IdCargo { get; set; }
        public int IdEstado { get; set; }
        public string Nombre { get; set; }
        public string ApePaterno { get; set; }
        public string ApeMaterno { get; set; }
        public int IdDocumento { get; set; }
        public string NroDocumento { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaCese { get; set; }
        public string UsuRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string UsuModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual ICollection<AsignacionBienMueble> AsignacionBienMueble { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual ICollection<ReciboProvisional> ReciboProvisional { get; set; }
        public virtual ICollection<SolicitudInformacionMunicipal> SolicitudInformacionMunicipal { get; set; }
        public virtual Area Area { get; set; }
        public virtual Cargo Cargo { get; set; }
    }
}
