//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Dominio.Servicio.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GrupoTabla {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GrupoTabla() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sismuni.Dominio.Servicio.Recursos.GrupoTabla", typeof(GrupoTabla).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0006.
        /// </summary>
        public static string EstadoReciboProvisional {
            get {
                return ResourceManager.GetString("EstadoReciboProvisional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0010.
        /// </summary>
        public static string EstadoSolicitudPagoServicio {
            get {
                return ResourceManager.GetString("EstadoSolicitudPagoServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0005.
        /// </summary>
        public static string EstadosSolicitud {
            get {
                return ResourceManager.GetString("EstadosSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0004.
        /// </summary>
        public static string ModoEnvio {
            get {
                return ResourceManager.GetString("ModoEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0001.
        /// </summary>
        public static string TipoDocumento {
            get {
                return ResourceManager.GetString("TipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0002.
        /// </summary>
        public static string TipoExpediente {
            get {
                return ResourceManager.GetString("TipoExpediente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0003.
        /// </summary>
        public static string TipoInformacionMunicipal {
            get {
                return ResourceManager.GetString("TipoInformacionMunicipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0009.
        /// </summary>
        public static string TipoMoneda {
            get {
                return ResourceManager.GetString("TipoMoneda", resourceCulture);
            }
        }
    }
}
